### ISSUE TITLE
RuntimeError: You need to use a gevent-socketio server.

### ISSUE THREAD

**Issue by nabinkhadka** [timmyreilly/Demo-Flask-SocketIO#1]
I am getting this exception when client tries to connect to the server.

Traceback (most recent call last):
  File "/home/nkhadka/ubuntu/Manuel_Godoy/first_receive/real_time_dashboard/penv/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/home/nkhadka/ubuntu/Manuel_Godoy/first_receive/real_time_dashboard/penv/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 494, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/home/nkhadka/ubuntu/Manuel_Godoy/first_receive/real_time_dashboard/penv/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 27, in __call__
    raise RuntimeError('You need to use a gevent-socketio server.')
RuntimeError: You need to use a gevent-socketio server.

Please let me know how to solve this issue. Thank you

**Comment by nabinkhadka** [comment]
Solved this issue using different version of socket-io.js. It was 0.9.16 instead of 1.X.X.
